= Themenrepo-Checkout und Konfiguration
:page-layout: docs
:toc: macro
:toclevels: 2

toc::[]

== Globale Plugin-Konfiguration

Das Plugin konfiguriert global:

* `displayName`
* `urlName`
* `topicRepositoryUrl`
* `topicRepositoryBranch`
* `topicRepositoryPath` als Legacy-Fallback

Wenn eine Git-URL gesetzt ist, arbeitet das Plugin bevorzugt mit einem
verwalteten Checkout. Nur wenn keine Git-URL vorhanden ist, greift der alte
lokale Pfad-Fallback.

== Verwalteter Checkout

Der verwaltete Checkout liegt unter:

* `JENKINS_HOME/gretl-datenportal/topic-repo`

Der Update-Ablauf fuer einen bereits existierenden Checkout ist absichtlich
streng:

. `git remote set-url origin <url>`
. `git fetch --prune origin`
. `git checkout -B <branch> origin/<branch>`
. `git reset --hard origin/<branch>`
. `git clean -fd`

Damit entspricht der verwaltete Checkout exakt dem konfigurierten Remote-Stand.

== Auswirkungen fuer lokale Entwicklung

Das Plugin verwaltet nur seinen eigenen Jenkins-internen Checkout. Das lokale
Arbeitsverzeichnis ausserhalb von Jenkins bleibt davon unberuehrt.

Fuer lokale End-to-End-Tests setzt `datenportal-jenkins-dev` standardmaessig:

* `topicRepositoryUrl=file://...`
* `topicRepositoryBranch=main`

Dadurch testet Jenkins gegen ein lokales Git-Repository, aber weiterhin ueber
denselben Checkout-Mechanismus wie spaeter im Betrieb.

== Weiterfuehrend

* Der fachliche Inhalt des ausgecheckten Repos ist im Repo
  link:https://codeberg.org/edigonzales/datenportal-themenrepo[datenportal-themenrepo]
  dokumentiert.
* Die lokale Jenkins-Konfiguration, die diese Werte setzt, liegt im Repo
  link:https://codeberg.org/edigonzales/datenportal-jenkins-dev[datenportal-jenkins-dev].
