= Lokale Entwicklung
:page-layout: docs
:toc: macro
:toclevels: 2

toc::[]

== Plugin bauen

```bash
cd ../datenportal-jenkins-gretl-plugin
export JAVA_HOME="${JAVA21_HOME:-$HOME/.sdkman/candidates/java/current}"
export PATH="$JAVA_HOME/bin:$PATH"
mvn -ntp package
```

Die Tests und das HPI laufen auf Java 21.

== In die lokale Jenkins-Umgebung integrieren

```bash
cd ../datenportal-jenkins-dev
./bin/install-gretl-datenportal-plugin.sh
./bin/start.sh
```

Für Änderungen am lokalen Themenrepo einschließlich uncommitteter und
untracked Dateien:

[source,bash]
----
THEMEN_REPO_MODE=working-tree ./bin/start.sh
----

Der Seed-Lauf erstellt daraus einen Snapshot unter
`JENKINS_HOME/gretl-datenportal/topic-repo`. Das externe Themenrepo bleibt
unverändert. Nach einer weiteren Änderung muss der Seed-Job erneut laufen; ein
laufender Job sieht nicht automatisch den aktuellen Arbeitsbaum.

Nach einer Plugin-Änderung: HPI bauen, installieren, Jenkins vollständig neu
starten und anschließend erneut seeden. Für einen isolierten Jenkins-Controller
steht `datenportal-jenkins-dev/bin/start-fresh.sh` zur Verfügung.

Danach in Jenkins:

. den automatisch angelegten Job `gretl-datenportal-seed` manuell starten oder
  auf den Cron-Lauf warten;
. `/gretl-datenportal` oeffnen;
. eine Organisation und einen Datensatz waehlen;
. entweder eine Datei liefern oder «Datenblatt aus Repository übernehmen» wählen;
. den generierten Job starten.

== Was lokal verifiziert werden sollte

Typische manuelle Pruefpunkte:

* Scan-Meldungen und Seed-Fehlerverhalten;
* Sichtbarkeit von Organisationen ueber `permissions.read`;
* Startberechtigung ueber `permissions.build`;
* Jenkinsfile-Aufloesung und Placeholder im repo-weiten Default;
* Weitergabe von Upload-Dateien und Parametern an den generierten Job.

== Weiterfuehrend

* Die lokale Jenkins- und Docker-Umgebung liegt im Repo
  link:https://codeberg.org/edigonzales/datenportal-jenkins-dev[datenportal-jenkins-dev].
* Der fachliche Inhalt, gegen den getestet wird, liegt im Repo
  link:https://codeberg.org/edigonzales/datenportal-themenrepo[datenportal-themenrepo].
